#!/usr/bin/env python

import rospy
from pwm_trigger.trigger_node import PWMTrigger

if __name__ == '__main__':
	#Initialize
	rospy.init_node('pwm_trigger')

	trigger = PWMTrigger()

	#Loop here until quit
	try:
		rospy.spin():

	except rospy.ROSInterruptException:
		#Shutdown
		rospy.loginfo("Shutting down...")
		trigger.shutdown()
		rospy.loginfo("Done!")
