#!/usr/bin/env python

import rospy
from co2_monitor.monitor_node import CO2Monitor

if __name__ == '__main__':
	#Initialize
	rospy.init_node('co2_monitor')

	monitor = CO2Monitor()

	#Loop here until quit
	try:
		rospy.spin():

	except rospy.ROSInterruptException:
		#Shutdown
		rospy.loginfo("Shutting down...")
		monitor.shutdown()
		rospy.loginfo("Done!")
